using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using MySql.Data.MySqlClient;

namespace DST
{
    public class CreacionBD
    {
        public CreacionBD(string usuario, string password)
        {
            MySqlConnectionStringBuilder builder = new MySqlConnectionStringBuilder();
            builder.Server = "localhost";
            builder.UserID = usuario;
            builder.Password = password;
            //builder.Database = "bddst";

            MySqlConnection conn = new MySqlConnection(builder.ToString());
            MySqlCommand cmd = conn.CreateCommand();

            cmd.CommandText = "CREATE DATABASE IF NOT EXISTS bddst;";
            conn.Open();
            cmd.ExecuteNonQuery();

            cmd.CommandText = "USE bddst;";
            cmd.ExecuteNonQuery();

            cmd.CommandText = "CREATE TABLE IF NOT EXISTS empresa("
            + "nombre text,"
            + "razonSocial varchar(12),"
            + "direccion text,"
            + "primary key(razonSocial)"
            + ");";
            cmd.ExecuteNonQuery();

            cmd.CommandText = "CREATE TABLE IF NOT EXISTS usuarios("
            + "nombre text,"
            + "rut varchar(12),"
            + "clave varchar (20),"
            + "tipoUsuario varchar(30),"
            + "estado boolean,"
            + "primary key(rut)"
            + ");";
            cmd.ExecuteNonQuery();

            cmd.CommandText = "CREATE TABLE IF NOT EXISTS secciones("
            + "id MEDIUMINT NOT NULL AUTO_INCREMENT,"
            + "nombre text,"
            + "rutJefe varchar(12),"
            + "tipoSeccion varchar (50),"
            + "primary key(id),"
            + "foreign key(rutJefe) references usuarios(rut)"
            + "on delete NO ACTION on update CASCADE"
            + ");";
            cmd.ExecuteNonQuery();

            cmd.CommandText = "CREATE TABLE IF NOT EXISTS trabajadores("
            + "rut varchar(12),"
            + "nombre varchar(50),"
            + "apellidoPaterno varchar(30),"
            + "apellidoMaterno varchar(30),"
            + "fechaNacimiento date,"
            + "idSeccion MEDIUMINT NOT NULL,"
            + "sexo varchar(10),"
            + "estado boolean,"
            + "primary key(rut),"
            + "foreign key(idSeccion) references secciones(id)"
            + "on delete CASCADE on update CASCADE"
            + ");";
            cmd.ExecuteNonQuery();

            cmd.CommandText = "CREATE TABLE IF NOT EXISTS componentesPerfil("
            + "id varchar (100),"
            + "nombre varchar(100),"
            + "descripcion text,"
            + "tipo varchar(20),"
            + "estado boolean,"
            + "primary key(id, nombre)"
            + ");";
            cmd.ExecuteNonQuery();

            cmd.CommandText = "CREATE TABLE IF NOT EXISTS componentesPerfilSecciones("
            + "idSeccion MEDIUMINT NOT NULL,"
            + "id varchar(100),"
            + "puntaje double,"
            + "importancia double,"
            + "estado boolean,"
            + "primary key(idSeccion, id),"
            + "foreign key(idSeccion) references secciones(id)"
            + "on delete CASCADE on update CASCADE,"
            + "foreign key(id) references componentesPerfil(id)"
            + "on delete CASCADE on update CASCADE"
            + ");";
            cmd.ExecuteNonQuery();

            cmd.CommandText = "CREATE TABLE IF NOT EXISTS componentesPerfilTrabajadores("
            + "rut varchar(12),"
            + "id varchar(100),"
            + "puntaje double,"
            + "primary key(rut, id),"
            + "foreign key(rut) references trabajadores(rut)"
            + "on delete CASCADE on update CASCADE,"
            + "foreign key(id) references componentesPerfil(id)"
            + "on delete CASCADE on update CASCADE"
            + ");";
            cmd.ExecuteNonQuery();

            cmd.CommandText = "CREATE TABLE IF NOT EXISTS desempeño("
            + "idSeccion MEDIUMINT NOT NULL,"
            + "fecha date,"
            + "ventasAñoActual double,"
            + "ventasAñoAnterior double,"
            + "ventasPlan double,"
            + "reubicaciones integer,"
            + "totalEmpleados integer,"
            + "empleadosCapacitados integer,"
            + "empleadosNoCapacitados integer,"
            + "primary key(idSeccion, fecha),"
            + "foreign key(idSeccion)references secciones(id)"
            + "on delete CASCADE on update CASCADE"
            + ");";
            cmd.ExecuteNonQuery();

            cmd.CommandText = "CREATE TABLE IF NOT EXISTS desempeñoGQM("
            + "idSeccion MEDIUMINT NOT NULL,"
            + "fecha date,"
            + "desempeño double,"
            + "reubicaciones integer,"
            + "totalEmpleados integer,"
            + "empleadosCapacitados integer,"
            + "empleadosNoCapacitados integer,"
            + "primary key(idSeccion, fecha),"
            + "foreign key(idSeccion)references secciones(id)"
            + "on delete CASCADE on update CASCADE"
            + ");";
            cmd.ExecuteNonQuery();

            cmd.CommandText = "CREATE TABLE IF NOT EXISTS reubicaciones("
            + "rut varchar(12),"
            + "idSeccionAnterior MEDIUMINT NOT NULL,"
            + "idSeccionNueva MEDIUMINT NOT NULL,"
            + "fecha date,"
            + "primary key(idSeccionAnterior, idSeccionNueva, fecha),"
            + "foreign key(rut) references trabajadores(rut)"
            + "on delete CASCADE on update CASCADE,"
            + "foreign key(idSeccionAnterior) references secciones(id)"
            + "on delete CASCADE on update CASCADE,"
            + "foreign key(idSeccionNueva) references secciones(id)"
            + "on delete CASCADE on update CASCADE"
            + ");";
            cmd.ExecuteNonQuery();

            cmd.CommandText = "CREATE TABLE IF NOT EXISTS preguntas("
            + "id MEDIUMINT NOT NULL AUTO_INCREMENT,"
            + "pregunta text,"
            + "tipo varchar(20),"
            + "estado boolean,"
            + "primary key(id)"
            + ");";
            cmd.ExecuteNonQuery();

            cmd.CommandText = "CREATE TABLE IF NOT EXISTS alternativas("
            + "alternativa varchar (100),"
            + "descripcion varchar(100),"
            + "valor double,"
            + "tipo varchar(20),"
            + "primary key(alternativa)"
            + ");";
            cmd.ExecuteNonQuery();

            cmd.CommandText = "CREATE TABLE IF NOT EXISTS alternativasPreguntas("
            + "idPregunta MEDIUMINT NOT NULL,"
            + "alternativa varchar(100),"
            + "primary key(idPregunta, alternativa),"
            + "foreign key(alternativa) references alternativas(alternativa)"
            + "on delete CASCADE on update CASCADE,"
            + "foreign key(idPregunta) references preguntas(id)"
            + "on delete CASCADE on update CASCADE"
            + ");";
            cmd.ExecuteNonQuery();

            cmd.CommandText = "CREATE TABLE IF NOT EXISTS componentesPreguntas("
            + "idPregunta MEDIUMINT NOT NULL,"
            + "idComponente varchar(100),"
            + "primary key(idPregunta, idComponente),"
            + "foreign key(idPregunta) references preguntas(id)"
            + "on delete CASCADE on update CASCADE,"
            + "foreign key(idComponente) references componentesPerfil(id)"
            + "on delete CASCADE on update CASCADE"
            + ");";
            cmd.ExecuteNonQuery();

            cmd.CommandText = "CREATE TABLE IF NOT EXISTS respuestas("
            + "idPregunta MEDIUMINT NOT NULL,"
            + "rutTrabajadorAsociado varchar(12),"
            + "rutRespuesta varchar(12),"
            + "alternativaRespuesta varchar(100),"
            + "primary key(idPregunta, rutTrabajadorAsociado, rutRespuesta),"
            + "foreign key(idPregunta) references preguntas(id)"
            + "on delete CASCADE on update CASCADE,"
            + "foreign key(rutTrabajadorAsociado) references trabajadores(rut)"
            + "on delete CASCADE on update CASCADE"
            + ");";
            cmd.ExecuteNonQuery();

            cmd.CommandText = "CREATE TABLE IF NOT EXISTS respuestas360("
            + "idPregunta MEDIUMINT NOT NULL,"
            + "rutTrabajadorAsociado varchar(12),"
            + "rutRespuesta varchar(12),"
            + "alternativaGrado varchar(100),"
            + "alternativaFrecuencia varchar(100),"
            + "resultadoRespuesta double,"
            + "primary key(idPregunta, rutTrabajadorAsociado, rutRespuesta),"
            + "foreign key(idPregunta) references preguntas(id)"
            + "on delete CASCADE on update CASCADE,"
            + "foreign key(rutTrabajadorAsociado) references trabajadores(rut)"
            + "on delete CASCADE on update CASCADE"
            + ");";
            cmd.ExecuteNonQuery();

            cmd.CommandText = "CREATE TABLE IF NOT EXISTS regla("
            + "id MEDIUMINT NOT NULL AUTO_INCREMENT,"
            + "idRegla integer,"
            + "operador varchar(20),"
            + "nombreVariable varchar (100),"
            + "nombreValor varchar(100),"
            + "tipoVariable varchar(20),"
            + "idSeccion  MEDIUMINT NOT NULL,"
            + "tipoComponente varchar(20),"
            + "primary key(id),"
            + "foreign key(idSeccion) references secciones(id)"
            + "on delete CASCADE on update CASCADE"
            + ");";
            cmd.ExecuteNonQuery();

            cmd.CommandText = "CREATE TABLE IF NOT EXISTS variablesLing("
            + "nombre varchar (100),"
            + "minimo double,"
            + "maximo double,"
            + "primary key(nombre),"
            + "foreign key(nombre) references componentesPerfil(id)"
            + "on delete CASCADE on update CASCADE"
            + ");";
            cmd.ExecuteNonQuery();

            cmd.CommandText = "CREATE TABLE IF NOT EXISTS valoresLing("
            + "nombre varchar (100),"
            + "nombreVariableLing varchar(100),"
            + "tipoFuncion varchar(20),"
            + "primary key(nombre, nombreVariableLing),"
            + "foreign key(nombreVariableLing) references componentesPerfil(id)"
            + "on delete CASCADE on update CASCADE"
            + ");";
            cmd.ExecuteNonQuery();

            cmd.CommandText = "CREATE TABLE IF NOT EXISTS funcionTrapezoide("
            + "nombreVariableLing varchar (100),"
            + "nombreValorLing varchar(100),"
            + "valorInferiorIzquierdo double,"
            + "valorSuperiorIzquierdo double,"
            + "valorSuperiorDerecho double,"
            + "valorInferiorDerecho double,"
            + "primary key(nombreVariableLing, nombreValorLing),"
            + "foreign key(nombreVariableLing) references componentesPerfil(id)"
            + "on delete CASCADE on update CASCADE"
            + ");";
            cmd.ExecuteNonQuery();

            cmd.CommandText = "CREATE TABLE IF NOT EXISTS funcionTriangular("
            + "nombreVariableLing varchar (100),"
            + "nombreValorLing varchar(100),"
            + "valorIzquierda double,"
            + "valorCentro double,"
            + "valorDerecha double,"
            + "primary key(nombreVariableLing, nombreValorLing),"
            + "foreign key(nombreVariableLing) references componentesPerfil(id)"
            + "on delete CASCADE on update CASCADE"
            + ");";
            cmd.ExecuteNonQuery();

            cmd.CommandText = "CREATE TABLE IF NOT EXISTS ventasAñoAnterior("
            + "idSeccion MEDIUMINT NOT NULL,"
            + "mes integer,"
            + "año integer,"
            + "ventasAñoAnterior double,"
            + "primary key(idSeccion, mes, año),"
            + "foreign key(idSeccion)references secciones(id)"
            + "on delete CASCADE on update CASCADE"
            + ");";
            cmd.ExecuteNonQuery();

            cmd.CommandText = "CREATE TABLE IF NOT EXISTS ventasPlan("
            + "idSeccion MEDIUMINT NOT NULL,"
            + "mes integer,"
            + "año integer,"
            + "ventasPlan double,"
            + "primary key(idSeccion, mes, año),"
            + "foreign key(idSeccion)references secciones(id)"
            + "on delete CASCADE on update CASCADE"
            + ");";
            cmd.ExecuteNonQuery();

            cmd.CommandText = "CREATE TABLE IF NOT EXISTS solicitudes("
            + "fechaSolicitud date,"
            + "estadoSolicitud varchar(20),"
            + "rutSolicitud varchar(12),"
            + "idSeccionActual MEDIUMINT NOT NULL,"
            + "idSeccionSolicitada MEDIUMINT NOT NULL,"
            + "capacidadSeccionActual double,"
            + "capacidadNuevaSeccion double,"
            + "primary key(fechaSolicitud, idSeccionActual, idSeccionSolicitada),"
            + "foreign key(idSeccionActual) references secciones(id)"
            + "on delete CASCADE on update CASCADE,"
            + "foreign key(idSeccionSolicitada) references secciones(id)"
            + "on delete CASCADE on update CASCADE"
            + ");";
            cmd.ExecuteNonQuery();

            cmd.CommandText = "CREATE TABLE IF NOT EXISTS evaluacionSeccion("
            + "fechaEvaluacion date,"
            + "idSeccion MEDIUMINT NOT NULL,"
            + "hb double,"
            + "hd double,"
            + "cf double,"
            + "primary key(fechaEvaluacion, idSeccion),"
            + "foreign key(idSeccion)references secciones(id)"
            + "on delete CASCADE on update CASCADE"
            + ");";
            cmd.ExecuteNonQuery();

            cmd.CommandText = "CREATE TABLE IF NOT EXISTS evaluacionTrabajador("
            + "fechaEvaluacion date,"
            + "rutTrabajador varchar(12),"
            + "hb double,"
            + "hd double,"
            + "cf double,"
            + "idSeccion MEDIUMINT NOT NULL,"
            + "primary key(fechaEvaluacion, rutTrabajador, idSeccion),"
            + "foreign key(rutTrabajador) references trabajadores(rut)"
            + "on delete CASCADE on update CASCADE,"
            + "foreign key(idSeccion) references secciones(id)"
            + "on delete CASCADE on update CASCADE"
            + ");";
            cmd.ExecuteNonQuery();

            cmd.CommandText = "CREATE TABLE IF NOT EXISTS capacidadTrabajador("
            + "rutTrabajador varchar(12),"
            + "idSeccionEvaluacion MEDIUMINT NOT NULL,"
            + "capacidadTrabajador double,"
            + "gradoIgualdadHB double,"
            + "gradoIgualdadHD double,"
            + "gradoIgualdadCF double,"
            + "primary key(rutTrabajador, idSeccionEvaluacion),"
            + "foreign key(rutTrabajador) references trabajadores(rut)"
            + "on delete CASCADE on update CASCADE,"
            + "foreign key(idSeccionEvaluacion) references secciones(id)"
            + "on delete CASCADE on update CASCADE"
            + ");";
            cmd.ExecuteNonQuery();

            cmd.CommandText = "CREATE TABLE IF NOT EXISTS listaTrabajadoresEncuestados("
            + "rutTrabajadorEvaluado varchar(12),"
            + "rutTrabajadorEvaluador varchar(12),"
            + "primary key(rutTrabajadorEvaluado, rutTrabajadorEvaluador),"
            + "foreign key(rutTrabajadorEvaluado) references trabajadores(rut)"
            + "on delete NO ACTION on update CASCADE,"
            + "foreign key(rutTrabajadorEvaluador) references trabajadores(rut)"
            + "on delete NO ACTION on update CASCADE"
            + ");";
            cmd.ExecuteNonQuery();

            cmd.CommandText = "CREATE TABLE IF NOT EXISTS listaUsuariosEncuestados("
            + "rutTrabajadorEvaluado varchar(12),"
            + "rutUsuarioEvaluador varchar(12),"
            + "primary key(rutTrabajadorEvaluado, rutUsuarioEvaluador),"
            + "foreign key(rutTrabajadorEvaluado) references trabajadores(rut)"
            + "on delete CASCADE on update CASCADE,"
            + "foreign key(rutUsuarioEvaluador) references usuarios(rut)"
            + "on delete NO ACTION on update CASCADE"
            + ");";
            cmd.ExecuteNonQuery();

            cmd.CommandText = "CREATE TABLE IF NOT EXISTS preguntasSeccion("
            + "idSeccion MEDIUMINT NOT NULL,"
            + "idPregunta MEDIUMINT NOT NULL,"
            + "primary key(idSeccion, idPregunta),"
            + "foreign key(idSeccion) references secciones(id)"
            + "on delete CASCADE on update CASCADE,"
            + "foreign key(idPregunta) references preguntas(id)"
            + "on delete CASCADE on update CASCADE"
            + ");";
            cmd.ExecuteNonQuery();

            cmd.CommandText = "CREATE TABLE IF NOT EXISTS respuestasSeccion("
            + "idSeccion MEDIUMINT NOT NULL,"
            + "idPregunta MEDIUMINT NOT NULL,"
            + "alternativa varchar (100),"
            + "primary key(idSeccion, idPregunta),"
            + "foreign key(idSeccion) references secciones(id)"
            + "on delete CASCADE on update CASCADE,"
            + "foreign key(idPregunta) references preguntas(id)"
            + "on delete CASCADE on update CASCADE"
            + ");";
            cmd.ExecuteNonQuery();

            cmd.CommandText = "CREATE TABLE IF NOT EXISTS respuestasseccionEncuesta("
            + "idSeccion mediumint(9),"
            + "puntaje double,"
            + "idPregunta mediumint(9),"
            + "idHabilidad varchar(100),"
            + "tipoHabilidad varchar(100)"
            + ");";
            cmd.ExecuteNonQuery();


            cmd.CommandText = "INSERT INTO `componentesperfil` (`id`, `nombre`, `descripcion`, `tipo`, `estado`) VALUES"
            + "('adaptacion_cambio', 'Adaptación al cambio', 'Capacidad para adaptarse a los cambios, modificando si fuera necesario su propia conducta para alcanzar determinados objetivos, favorece el aprendizaje', 'hb', 1),"
            + "('almacenaje_traslado_mercaderia', 'Conocimiento de almacenaje y traslado de mercadería', 'No disponible', 'hd', 1),"
            + "('atencion_clientes', 'Experiencia en Atencion de clientes', 'No disponible', 'hd', 1),"
            + "('autocontrol', 'Autocontrol', 'Habilidad de dominar las propias emociones, comportamientos y deseos', 'hb', 1),"
            + "('CF', 'Caracteristicas Fisicas', 'No disponible', 'general', 1),"
            + "('conocimientos_matematicas', 'Conocimiento de matemáticas básicas', 'No disponible', 'hd', 1),"
            + "('conocimiento_cajas', 'Conocimiento de Sistema de cajas', 'No disponible', 'hd', 1),"
            + "('discapacidad_fisica', 'Discapacidad fisica', 'Aspecto con el que se muestra una persona.', 'cf', 1),"
            + "('disposicion_at_insumos', 'Conocimiento sobre la disposición de área de trabajo e insumos', 'No disponible', 'hd', 1),"
            + "('edad', 'Edad', 'Edad del trabjador', 'cf', 1),"
            + "('eficiencia', 'Eficiencia', 'Capacidad para realizar o cumplir adecuadamente una función', 'hb', 1),"
            + "('elaboracion_productos_panaderia', 'Conocimiento sobre la elaboración de productos de panadería según los procedimientos de la empresa', 'No disponible', 'hd', 1),"
            + "('empatia', 'Empatía', 'Capacidad de identificarse con alguien y compartir sus sentimientos (Ponerse en el lugar de los demás y ser solidario)', 'hb', 1),"
            + "('especificaciones_tecnicas', 'Conocimiento de especificaciones técnicas de los productos', 'No disponible', 'hd', 1),"
            + "('habilidad_lectoescritura', 'Habilidades Lectoescritura', 'No disponible', 'hd', 1),"
            + "('habilidad_logicomatematica', 'Habilidades lógico-matemáticas', 'No disponible', 'hd', 1),"
            + "('HB', 'Habilidades Blandas', 'No disponible', 'general', 1),"
            + "('HD', 'Habilidades Duras', 'No disponible', 'general', 1),"
            + "('hornear_masas', 'Conocimiento sobre hornear masas según los procedimientos de la empresa', 'No disponible', 'hd', 1),"
            + "('identificar_documentos_mercantiles', 'Capacidad para identificar documentos mercantiles', 'No disponible', 'hd', 1),"
            + "('integridad', 'Integridad', 'Cualidad de quien tiene entereza moral, rectitud y honradez en la conducta y el comportamiento', 'hb', 1),"
            + "('lenguaje_formal', 'Manejo de lenguaje formal', 'No disponible', 'hd', 1),"
            + "('moler_cortar_carne', 'Conocimiento sobre los procedimientos de moler y cortar carne', 'No disponible', 'hd', 1),"
            + "('motivacion', 'Motivación', 'Estímulo que mueve a una persona para realizar conductas e insistir en ellas para completarlas', 'hb', 1),"
            + "('normas_higiene_seguridad', 'Conocimiento de normas de higiene y seguridad', 'No disponible', 'hd', 1),"
            + "('normativa_procedimientos', 'Conocimiento de la normativa y procedimientos de la empresa', 'No disponible', 'hd', 1),"
            + "('norma_sanitaria_establecimientos', 'Conocimiento sobre la norma técnica sanitaria de establecimientos alimenticios', 'No disponible', 'hd', 1),"
            + "('pesaje_sellado_productos', 'Conocimiento sobre pesaje y sellado de productos', 'No disponible', 'hd', 1),"
            + "('preparacion_masas', 'Conocimiento sobre la preparación de masas según los procedimientos de la empresa', 'No disponible', 'hd', 1),"
            + "('presentacion_personal', 'Presentacion personal', 'El trabajador presenta algun impedimento para realizar el trabajo.', 'cf', 1),"
            + "('proactividad', 'Proactividad', 'Trabajador que tiene iniciativa y capacidad para anticiparse a problemas o necesidades futuras', 'hb', 1),"
            + "('respeto', 'Respeto', 'Consideración, acompañada de cierta sumisión, con que se trata a una persona o una cosa por alguna cualidad, situación o circunstancia que las determina y que lleva a acatar lo que dice o establece o a no causarle ofensa o perjuicio', 'hb', 1),"
            + "('responsabilidad', 'Responsabilidad', 'Responder a las exigencias del puesto, en los tiempos y formas establecidas', 'hb', 1),"
            + "('sistema_informatico', 'Conocimiento en el sistema informático de la empresa', 'No disponible', 'hd', 1),"
            + "('sociabilidad', 'Sociabilidad', 'Facilidad para poder relacionarse con cualquier persona de la organización en la que se trabaja y con distintos públicos fuera de ella', 'hb', 1),"
            + "('tecnicas_venta', 'Conocimiento Técnicas de venta', 'No disponible', 'hd', 1),"
            + "('tolerancia_presion', 'Tolerancia a la presión', 'Capacidad de soportar las situaciones que son estresantes o muy demandantes, permite sortear situaciones complejas y no perder el foco en lo importante', 'hb', 1),"
            + "('trabajo_equipo', 'Trabajo en equipo', 'Capacidad de tener la tolerancia y diplomacia suficientes como para lidiar con distintos tipos de personalidades', 'hb', 1); ";
            cmd.ExecuteNonQuery();


            cmd.CommandText = "INSERT INTO `preguntas` (`id`, `pregunta`, `tipo`, `estado`) VALUES"
            + "(1, 'Controla las emociones fuertes u otro estrés', 'Evaluacion 360', 1),"
            + "(2, 'En situaciones muy estresantes, calma a otros.', '360', 1),"
            + "(3, 'Evita involucrarse en conductas impulsivas.', '360', 1),"
            + "(4, 'Maneja el estrés y canaliza las energías hacia los objetivos', '360', 1),"
            + "(5, 'El trato hacia sus compañeros y superiores es amable y cortés', '360', 1),"
            + "(6, 'Escucha a los demás antes de expresar su propio punto de vista.', '360', 1),"
            + "(7, 'Trata a las personas de la misma manera, no importa la raza, religión, género, tamaño, edad,país u origen.', '360', 1),"
            + "(8, 'Se involucra para ayudar a los demás en sus problemas o dificultades.', '360', 1),"
            + "(9, 'Muestra interés en mantener un ambiente de trabajo agradable para todo el grupo.', '360', 1),"
            + "(10, 'Se preocupa por el bienestar de sus compañeros', '360', 1),"
            + "(11, 'Propone mejoras sobre los procesos y/o actividades de su área.', '360', 1),"
            + "(12, 'Inicia y lleva a cabo nuevos proyectos o tareas que van más allá de sus responsabilidades.', '360', 1),"
            + "(13, 'Toma la iniciativa para aprender nuevas habilidades que le ayudaran en su desempeño.', '360', 1),"
            + "(14, 'Se implica y compromete en el cumplimiento de sus tareas.', '360', 1),"
            + "(15, 'Es organizado y cuidadoso con la buena ejecución del trabajo', '360', 1),"
            + "(16, 'Asume siempre las consecuencias de lo que se hace, sean buenas o malas.', '360', 1),"
            + "(17, 'Alcanza los objetivos propuestos en situaciones de presión de tiempo, oposición y diversidad.', '360', 1),"
            + "(18, 'Su desempeño es alto en situaciones de mucha exigencia.', '360', 1),"
            + "(19, 'Puede priorizar las demandas con facilidad en contextos de mucha presión.', '360', 1),"
            + "(20, 'Su personalidad es extrovertida.', '360', 1),"
            + "(21, 'Se relaciona fácilmente con sus compañeros.', '360', 1),"
            + "(22, 'Su actuar no es individualista, y promueve el trabajo en grupo.', '360', 1),"
            + "(23, 'Se comunica cordialmente con las personas en todos los niveles, favoreciendo un ambiente de trabajo ameno.', '360', 1),"
            + "(24, 'Es flexible para manejar el cambio.', '360', 1),"
            + "(25, 'Se maneja con desenvoltura frente a las exigencias múltiples, prioridades cambiantes o mudanzas rapidas.', '360', 1),"
            + "(26, 'Adapta sus reacciones y tácticas en las circunstancias variables.', '360', 1),"
            + "(27, 'Es flexible en su visión de los hechos.', '360', 1),"
            + "(28, 'Alcanza los objetivos propuestos, solo utilizando los recursos necesarios.', '360', 1),"
            + "(29, 'Planifica bien sus tareas diarias y hace buen uso de su tiempo.', '360', 1),"
            + "(30, 'Generalmente es asertivo en sus decisiones.', '360', 1),"
            + "(31, 'Es honesto en lo que dice y hace.', '360', 1),"
            + "(32, 'Asume la responsabilidad de las acciones colectivas e individuales.', '360', 1),"
            + "(33, 'Asegura la transparencia en la administración de recursos asignados.', '360', 1),"
            + "(34, 'Comparte información y realiza valiosos aportes en las tareas con sus pares.', '360', 1),"
            + "(35, 'Participa y coopera en la consecución de objetivos grupales.', '360', 1),"
            + "(36, 'Incluye a otros en el proceso de decisión para obtener la información necesaria y tomar la mejor decisión; asegura que los otros respalden y entiendan las decisiones.', '360', 1),"
            + "(37, 'Se orienta hacia los resultados, con un gran afán de alcanzar objetivos o requisitos.', '360', 1),"
            + "(38, 'Acepta riesgos calculados.', '360', 1),"
            + "(39, 'Frente a las dificultades trata de encontrar rutas alternativas para lograr el resultado', '360', 1),"
            + "(40, 'Puede realizar las operaciones de suma y resta, sin mayor complicación.', '360', 1),"
            + "(41, 'Puede realizar las operaciones de division y multiplicacion sin mayor complicación.', '360', 1),"
            + "(42, 'Puede realizar operaciones matemáticas básicas mezcladas.', '360', 1),"
            + "(43, 'Demuestra conocimiento amplio con respecto a las normativas existentes en la empresa.', '360', 1),"
            + "(44, 'Conoce los protocolos que utiliza la empresa para resolver diversas situaciones.', '360', 1),"
            + "(45, 'Atiende cordialmente a los clientes, identificando las alternativas de soluciones posibles.', '360', 1),"
            + "(46, 'Resuelve situaciones de conflicto con clientes, manteniendo la tranquilidad, emitiendo mensajes conciliadores y asegurándose de ofrecer todas las alternativas disponibles para satisfacer las necesidades del cliente', '360', 1),"
            + "(47, 'Capta oportunamente los mensajes que recibe y emite mensajes claros que resuelvan exactamente las inquietudes del cliente.', '360', 1),"
            + "(48, 'Utiliza un lenguaje formal y evidencia un dominio de los procedimientos de la empresa.', '360', 1),"
            + "(49, 'Ejecuta sin mayor contratiempo las operaciones disponibles en el sistema.', '360', 1),"
            + "(50, 'Tiene conocimiento sobre qué hacer en caso de surgir un error en el sistema.', '360', 1),"
            + "(51, 'Tiene conocimiento sobre cómo rectificar un error al ejecutar una operación en el sistema.', '360', 1),"
            + "(52, 'Demuestra amplio conocimiento con respecto a los productos relacionados con su área.', '360', 1),"
            + "(53, 'Sus conocimientos sobre los productos lo hacen un referente para sus compañeros.', '360', 1),"
            + "(54, 'Al comunicarse con el cliente evita utilizar modismos, o muletillas.', '360', 1),"
            + "(55, 'Al relacionarse con el personal de trabajo, evita utilizar palabras groseras.', '360', 1),"
            + "(56, 'En su comunicación habitual utiliza palabras de cortesía como buenos días, buenas tardes, buenas noches, etc', '360', 1),"
            + "(57, 'Tiene la capacidad de realizar cálculos matemáticos mentalmente, sin mayor contratiempo.', '360', 1),"
            + "(58, 'Tiene la capacidad de identificar patrones matemáticos simples.', '360', 1),"
            + "(59, 'Tiene la capacidad de leer una instrucción simple e interpretarla.', '360', 1),"
            + "(60, 'Tiene la capacidad de replicar en la escritura lo que quiere comunicar verbalmente.', '360', 1),"
            + "(61, 'Tiene la capacidad de escribir una instrucción simple.', '360', 1),"
            + "(62, 'Administra los dineros responsablemente, cerciorándose de la cuadratura en cada una de las operaciones que realiza.', '360', 1),"
            + "(63, 'Los cobros con errores de precios son anulados de acuerdo procedimientos técnicos de sistema y protocolos de atención a clientes.', '360', 1),"
            + "(64, 'La caja registradora es abierta, de acuerdo a controles administrativos y de seguridad establecidos para el sector.', '360', 1),"
            + "(65, 'La apertura de caja es registrada de acuerdo a procedimientos de control administrativo y a los formatos de documentación de registro establecidos para el sector.', '360', 1),"
            + "(66, 'La boleta y vuelto son entregados a clientes de acuerdo a protocolos de atención a clientes, medios de pago utilizados y los procedimientos de caja establecidos en el sector.', '360', 1),"
            + "(67, 'Tiene la capacidad para identificar los distintos tipos de cheque.', '360', 1),"
            + "(68, 'Tiene la capacidad para identificar y distinguir entre tarjeta de crédito y tarjeta de débito.', '360', 1),"
            + "(69, 'Tiene la capacidad de identificar guías de despacho, facturas, notas de créditos y otros documentos asociados al área mercantil.', '360', 1),"
            + "(70, 'Demuestra conocimiento sobre las diversas señaléticas asociadas a elementos de seguridad.', '360', 1),"
            + "(71, 'Demuestra conocimiento sobre la normativa técnica sanitaria de Supermercados.', '360', 1),"
            + "(72, 'Demuestra conocimientos sobre protocolos a utilizar en caso de emergencias.', '360', 1),"
            + "(73, 'Realiza el procedimiento de sanitizar el piso, paredes y mesones según el protocolo de la empresa.', '360', 1),"
            + "(74, 'Deposita los materiales de desecho en los contenedores correspondientes, dispuestos por la empresa.', '360', 1),"
            + "(75, 'Examina la máquina moledora, asegurándose de que cumple con los estándares de calidad.', '360', 1),"
            + "(76, 'Traslada de manera correcta los distintos tipos de carne desde la cámara a la sala de procesos, y luego cumple con el procedimiento de molido y/o corte y pesaje, para luego registrarlas en planilla.', '360', 1),"
            + "(77, 'Realiza de manera correcta la molienda y corte de carne según  las especificaciones definidas.', '360', 1),"
            + "(78, 'Realiza de manera correcta el sellado y rotulado de bandejas de carne, ingresando códigos y valor por kilo.', '360', 1),"
            + "(79, 'Adhiere de manera correcta los datos al producto para su correcta identificación.', '360', 1),"
            + "(80, 'Abastece de manera correcta las salas y vitrinas ajustándose a lo establecido en el layout.', '360', 1),"
            + "(81, 'Chequea previamente, de manera correcta, la calidad y temperatura de los productos a ubicar en vitrina.', '360', 1),"
            + "(82, 'Utiliza correctamente los equipos y utensilios de la empresa.', '360', 1),"
            + "(83, 'Mantiene los equipos y utensilios en el lugar establecido, según procedimientos de la empresa.', '360', 1),"
            + "(84, 'Chequea de manera correcta las fechas de vigencia sanitaria y la presencia de sustancias contaminantes en materias primas e insumos, según los procedimientos de la empresa.', '360', 1),"
            + "(85, 'Identifica correctamente y de manera oportuna las materias primas e insumos que no cumplan con las normas sanitarias vigentes, y son retiradas según los procedimientos de la empresa.', '360', 1),"
            + "(86, 'Cumple con las instrucciones del jefe directo y se apega a los procedimientos, para abrir el quintal de harina y vaciarlo en la amasadora.', '360', 1),"
            + "(87, 'Calibra de manera correcta los equipos según los procedimientos de la empresa.', '360', 1),"
            + "(88, 'Incorpora de manera correcta a la máquina los ingredientes, en orden, tiempo y cantidad establecida, según ficha técnica.', '360', 1),"
            + "(89, 'Mide y comprueba de manera correcta la temperatura final de la masa con un termómetro, asegurándose de cumplir con la ficha técnica.', '360', 1),"
            + "(90, 'Chequea correctamente la presencia de elementos y/o contaminantes en la masa, según los procedimientos de la empresa.', '360', 1),"
            + "(91, 'Realiza correctamente la graduación de la maquinaria e incorpora la masa en la maquina sobadora, según la ficha técnica y procedimiento de la empresa.', '360', 1),"
            + "(92, 'Calibra correctamente el volumen y grosor de la masa según la ficha técnica.', '360', 1),"
            + "(93, 'Extrae e instala correctamente la masa sobada sobre el mesón enharinado, según los procedimientos de la empresa.', '360', 1),"
            + "(94, 'Realiza correctamente el proceso de enharinar, picar y cortar con molde, según la ficha técnica.', '360', 1),"
            + "(95, 'Limpia y aceita correctamente las latas, según los procedimientos de la empresa.', '360', 1),"
            + "(96, 'Ubica correctamente las masas cortadas en latas, según los procedimientos de la empresa.', '360', 1),"
            + "(97, 'Realiza correctamente el proceso de precalentar el horno y regular la temperatura, según la ficha técnica.', '360', 1),"
            + "(98, 'Tiene la capacidad de reconocer el punto óptimo de cocción de las masas, según la ficha técnica.', '360', 1),"
            + "(99, 'Identifica y corrige correctamente las anomalías presentes en las masas, según la ficha técnica.', '360', 1),"
            + "(100, 'Extrae y/o deposita los productos horneados en contenedores, correctamente, según los procedimientos de la empresa.', '360', 1),"
            + "(101, 'Los productos en cámara son rotados, según la fecha de llegada, evitando la merma por vencimiento.', '360', 1),"
            + "(102, 'La bodega está ordenada y las cajas de productos son apilados uniformemente, según el layout.', '360', 1),"
            + "(103, 'El formulario de stock es elaborado registrando con exactitud las especificaciones de los productos.', '360', 1),"
            + "(104, 'Asesora a los clientes de acuerdo a sus necesidades.', '360', 1),"
            + "(105, 'Atiende a la información planteada por el cliente.', '360', 1),"
            + "(106, 'Tiene buen manejo del tono de voz, y lenguaje no verbal ante los clientes.', '360', 1),"
            + "(107, 'Indaga asertivamente en las necesidades del cliente, identificando las alternativas que mejor se ajusten a sus requerimientos.', '360', 1),"
            + "(108, 'Ofrece al cliente asesoría personalizada, evidenciando un dominio de los diferentes productos disponibles y de sus características y especificaciones.', '360', 1);";
            cmd.ExecuteNonQuery();


            cmd.CommandText = "INSERT INTO `alternativas` (`alternativa`, `descripcion`, `valor`, `tipo`) VALUES"
            + "('Altamente competente', 'Muy eficiente en esta área de competencia. Excede las expectativas.', 75, 'grado'),"
            + "('Competente', 'Generalmente capacitado en esta área de competencia. Cumple las expectativas.', 50, 'grado'),"
            + "('Frecuente', 'Representa el comportamiento frecuente del evaluado.', 75, 'frecuencia'),"
            + "('La mitad del tiempo', 'Representa el comportamiento en la mitad de las ocasiones', 55, 'frecuencia'),"
            + "('Modelo de rol', 'Establece un estándar en esta área de competencia. (Es visto por los otros como un modelo o mentor e', 100, 'grado'),"
            + "('Necesita desarrollarse', 'Necesita algunas mejoras para ser eficiente en esta área de competencia.', 25, 'grado'),"
            + "('Necesita desarrollarse significativamente', 'Necesita significativas mejoras para lograr eficiencia en esta área de competencia.', 0, 'grado'),"
            + "('No puede ser evaluado', 'Esta área no puede ser evaluada (por ejemplo no hubo oportunidad para observarlo o esta área de comp', -1, 'grado'),"
            + "('Ocasional', 'Representa el comportamiento ocasional del evaluado', 25, 'frecuencia'),"
            + "('Siempre', 'Representa el comportamiento habitual del evaluado. Siempre se comporta de ese modo.', 100, 'frecuencia');";
            cmd.ExecuteNonQuery();


            cmd.CommandText = "INSERT INTO `componentespreguntas` (`idPregunta`, `idComponente`) VALUES"
            + "(1, 'integridad'),"
            + "(2, 'autocontrol'),"
            + "(3, 'autocontrol'),"
            + "(4, 'autocontrol'),"
            + "(5, 'respeto'),"
            + "(6, 'respeto'),"
            + "(7, 'respeto'),"
            + "(8, 'empatia'),"
            + "(9, 'empatia'),"
            + "(10, 'empatia'),"
            + "(11, 'proactividad'),"
            + "(12, 'proactividad'),"
            + "(13, 'proactividad'),"
            + "(14, 'responsabilidad'),"
            + "(15, 'responsabilidad'),"
            + "(16, 'responsabilidad'),"
            + "(17, 'tolerancia_presion'),"
            + "(18, 'tolerancia_presion'),"
            + "(19, 'tolerancia_presion'),"
            + "(20, 'sociabilidad'),"
            + "(21, 'sociabilidad'),"
            + "(22, 'sociabilidad'),"
            + "(23, 'sociabilidad'),"
            + "(24, 'adaptacion_cambio'),"
            + "(25, 'adaptacion_cambio'),"
            + "(26, 'adaptacion_cambio'),"
            + "(27, 'adaptacion_cambio'),"
            + "(28, 'eficiencia'),"
            + "(29, 'eficiencia'),"
            + "(30, 'eficiencia'),"
            + "(31, 'integridad'),"
            + "(32, 'integridad'),"
            + "(33, 'integridad'),"
            + "(34, 'trabajo_equipo'),"
            + "(35, 'trabajo_equipo'),"
            + "(36, 'trabajo_equipo'),"
            + "(37, 'motivacion'),"
            + "(38, 'motivacion'),"
            + "(39, 'motivacion'),"
            + "(40, 'conocimientos_matematicas'),"
            + "(41, 'conocimientos_matematicas'),"
            + "(42, 'conocimientos_matematicas'),"
            + "(43, 'normativa_procedimientos'),"
            + "(44, 'normativa_procedimientos'),"
            + "(45, 'atencion_clientes'),"
            + "(46, 'atencion_clientes'),"
            + "(47, 'atencion_clientes'),"
            + "(48, 'atencion_clientes'),"
            + "(49, 'sistema_informatico'),"
            + "(50, 'sistema_informatico'),"
            + "(51, 'sistema_informatico'),"
            + "(52, 'especificaciones_tecnicas'),"
            + "(53, 'especificaciones_tecnicas'),"
            + "(54, 'lenguaje_formal'),"
            + "(55, 'lenguaje_formal'),"
            + "(56, 'lenguaje_formal'),"
            + "(57, 'habilidad_logicomatematica'),"
            + "(58, 'habilidad_logicomatematica'),"
            + "(59, 'habilidad_lectoescritura'),"
            + "(60, 'habilidad_lectoescritura'),"
            + "(61, 'habilidad_lectoescritura'),"
            + "(62, 'conocimiento_cajas'),"
            + "(63, 'conocimiento_cajas'),"
            + "(64, 'conocimiento_cajas'),"
            + "(65, 'conocimiento_cajas'),"
            + "(66, 'conocimiento_cajas'),"
            + "(67, 'identificar_documentos_mercantiles'),"
            + "(68, 'identificar_documentos_mercantiles'),"
            + "(69, 'identificar_documentos_mercantiles'),"
            + "(70, 'normas_higiene_seguridad'),"
            + "(71, 'normas_higiene_seguridad'),"
            + "(72, 'normas_higiene_seguridad'),"
            + "(73, 'norma_sanitaria_establecimientos'),"
            + "(74, 'norma_sanitaria_establecimientos'),"
            + "(75, 'moler_cortar_carne'),"
            + "(76, 'moler_cortar_carne'),"
            + "(77, 'moler_cortar_carne'),"
            + "(78, 'moler_cortar_carne'),"
            + "(79, 'pesaje_sellado_productos'),"
            + "(80, 'pesaje_sellado_productos'),"
            + "(81, 'pesaje_sellado_productos'),"
            + "(82, 'disposicion_at_insumos'),"
            + "(83, 'disposicion_at_insumos'),"
            + "(84, 'disposicion_at_insumos'),"
            + "(85, 'disposicion_at_insumos'),"
            + "(86, 'preparacion_masas'),"
            + "(87, 'preparacion_masas'),"
            + "(88, 'preparacion_masas'),"
            + "(89, 'preparacion_masas'),"
            + "(90, 'preparacion_masas'),"
            + "(91, 'elaboracion_productos_panaderia'),"
            + "(92, 'elaboracion_productos_panaderia'),"
            + "(93, 'elaboracion_productos_panaderia'),"
            + "(94, 'elaboracion_productos_panaderia'),"
            + "(95, 'elaboracion_productos_panaderia'),"
            + "(96, 'elaboracion_productos_panaderia'),"
            + "(97, 'hornear_masas'),"
            + "(98, 'hornear_masas'),"
            + "(99, 'hornear_masas'),"
            + "(100, 'hornear_masas'),"
            + "(101, 'almacenaje_traslado_mercaderia'),"
            + "(102, 'almacenaje_traslado_mercaderia'),"
            + "(103, 'almacenaje_traslado_mercaderia'),"
            + "(104, 'tecnicas_venta'),"
            + "(105, 'tecnicas_venta'),"
            + "(106, 'tecnicas_venta'),"
            + "(107, 'tecnicas_venta'),"
            + "(108, 'tecnicas_venta');";
            cmd.ExecuteNonQuery();

            cmd.CommandText = "INSERT INTO `variablesling` (`nombre`, `minimo`, `maximo`) VALUES"
            + "('adaptacion_cambio', 0, 100),"
            + "('almacenaje_traslado_mercaderia', 0, 100),"
            + "('atencion_clientes', 0, 100),"
            + "('autocontrol', 0, 100),"
            + "('conocimientos_matematicas', 0, 100),"
            + "('conocimiento_cajas', 0, 100),"
            + "('discapacidad_fisica', 0, 100),"
            + "('disposicion_at_insumos', 0, 100),"
            + "('edad', 18, 60),"
            + "('eficiencia', 0, 100),"
            + "('elaboracion_productos_panaderia', 0, 100),"
            + "('empatia', 0, 100),"
            + "('especificaciones_tecnicas', 0, 100),"
            + "('habilidad_lectoescritura', 0, 100),"
            + "('habilidad_logicomatematica', 0, 100),"
            + "('hornear_masas', 0, 100),"
            + "('identificar_documentos_mercantiles', 0, 100),"
            + "('integridad', 0, 100),"
            + "('lenguaje_formal', 0, 100),"
            + "('moler_cortar_carne', 0, 100),"
            + "('motivacion', 0, 100),"
            + "('normas_higiene_seguridad', 0, 100),"
            + "('normativa_procedimientos', 0, 100),"
            + "('norma_sanitaria_establecimientos', 0, 100),"
            + "('pesaje_sellado_productos', 0, 100),"
            + "('preparacion_masas', 0, 100),"
            + "('presentacion_personal', 0, 100),"
            + "('proactividad', 0, 100),"
            + "('respeto', 0, 100),"
            + "('responsabilidad', 0, 100),"
            + "('sistema_informatico', 0, 100),"
            + "('sociabilidad', 0, 100),"
            + "('tecnicas_venta', 0, 100),"
            + "('tolerancia_presion', 0, 100),"
            + "('trabajo_equipo', 0, 100); ";
            cmd.ExecuteNonQuery();

            cmd.CommandText = "INSERT INTO `valoresling` (`nombre`, `nombreVariableLing`, `tipoFuncion`) VALUES"
            + "('Adolescente', 'edad', 'triangular'),"
            + "('Adulto', 'edad', 'triangular'),"
            + "('Adulto_mayor', 'edad', 'triangular'),"
            + "('Alta', 'adaptacion_cambio', 'triangular'),"
            + "('Alta', 'almacenaje_traslado_mercaderia', 'triangular'),"
            + "('Alta', 'atencion_clientes', 'triangular'),"
            + "('Alta', 'autocontrol', 'triangular'),"
            + "('Alta', 'conocimientos_matematicas', 'triangular'),"
            + "('Alta', 'conocimiento_cajas', 'triangular'),"
            + "('Alta', 'disposicion_at_insumos', 'triangular'),"
            + "('Alta', 'eficiencia', 'triangular'),"
            + "('Alta', 'elaboracion_productos_panaderia', 'triangular'),"
            + "('Alta', 'empatia', 'triangular'),"
            + "('Alta', 'especificaciones_tecnicas', 'triangular'),"
            + "('Alta', 'habilidad_lectoescritura', 'triangular'),"
            + "('Alta', 'habilidad_logicomatematica', 'triangular'),"
            + "('Alta', 'hornear_masas', 'triangular'),"
            + "('Alta', 'identificar_documentos_mercantiles', 'triangular'),"
            + "('Alta', 'integridad', 'triangular'),"
            + "('Alta', 'lenguaje_formal', 'triangular'),"
            + "('Alta', 'moler_cortar_carne', 'triangular'),"
            + "('Alta', 'motivacion', 'triangular'),"
            + "('Alta', 'normas_higiene_seguridad', 'triangular'),"
            + "('Alta', 'normativa_procedimientos', 'triangular'),"
            + "('Alta', 'norma_sanitaria_establecimientos', 'triangular'),"
            + "('Alta', 'pesaje_sellado_productos', 'triangular'),"
            + "('Alta', 'preparacion_masas', 'triangular'),"
            + "('Alta', 'presentacion_personal', 'triangular'),"
            + "('Alta', 'proactividad', 'triangular'),"
            + "('Alta', 'respeto', 'triangular'),"
            + "('Alta', 'responsabilidad', 'triangular'),"
            + "('Alta', 'sistema_informatico', 'triangular'),"
            + "('Alta', 'sociabilidad', 'triangular'),"
            + "('Alta', 'tecnicas_venta', 'triangular'),"
            + "('Alta', 'tolerancia_presion', 'triangular'),"
            + "('Alta', 'trabajo_equipo', 'triangular'),"
            + "('Baja', 'adaptacion_cambio', 'triangular'),"
            + "('Baja', 'almacenaje_traslado_mercaderia', 'triangular'),"
            + "('Baja', 'atencion_clientes', 'triangular'),"
            + "('Baja', 'autocontrol', 'triangular'),"
            + "('Baja', 'conocimientos_matematicas', 'triangular'),"
            + "('Baja', 'conocimiento_cajas', 'triangular'),"
            + "('Baja', 'disposicion_at_insumos', 'triangular'),"
            + "('Baja', 'eficiencia', 'triangular'),"
            + "('Baja', 'elaboracion_productos_panaderia', 'triangular'),"
            + "('Baja', 'empatia', 'triangular'),"
            + "('Baja', 'especificaciones_tecnicas', 'triangular'),"
            + "('Baja', 'habilidad_lectoescritura', 'triangular'),"
            + "('Baja', 'habilidad_logicomatematica', 'triangular'),"
            + "('Baja', 'hornear_masas', 'triangular'),"
            + "('Baja', 'identificar_documentos_mercantiles', 'triangular'),"
            + "('Baja', 'integridad', 'triangular'),"
            + "('Baja', 'lenguaje_formal', 'triangular'),"
            + "('Baja', 'moler_cortar_carne', 'triangular'),"
            + "('Baja', 'motivacion', 'triangular'),"
            + "('Baja', 'normas_higiene_seguridad', 'triangular'),"
            + "('Baja', 'normativa_procedimientos', 'triangular'),"
            + "('Baja', 'norma_sanitaria_establecimientos', 'triangular'),"
            + "('Baja', 'pesaje_sellado_productos', 'triangular'),"
            + "('Baja', 'preparacion_masas', 'triangular'),"
            + "('Baja', 'presentacion_personal', 'triangular'),"
            + "('Baja', 'proactividad', 'triangular'),"
            + "('Baja', 'respeto', 'triangular'),"
            + "('Baja', 'responsabilidad', 'triangular'),"
            + "('Baja', 'sistema_informatico', 'triangular'),"
            + "('Baja', 'sociabilidad', 'triangular'),"
            + "('Baja', 'tecnicas_venta', 'triangular'),"
            + "('Baja', 'tolerancia_presion', 'triangular'),"
            + "('Baja', 'trabajo_equipo', 'triangular'),"
            + "('Joven_adulto', 'edad', 'triangular'),"
            + "('Muy_alta', 'adaptacion_cambio', 'trapezoidal'),"
            + "('Muy_alta', 'almacenaje_traslado_mercaderia', 'trapezoidal'),"
            + "('Muy_alta', 'atencion_clientes', 'trapezoidal'),"
            + "('Muy_alta', 'autocontrol', 'trapezoidal'),"
            + "('Muy_alta', 'conocimientos_matematicas', 'trapezoidal'),"
            + "('Muy_alta', 'conocimiento_cajas', 'trapezoidal'),"
            + "('Muy_alta', 'disposicion_at_insumos', 'trapezoidal'),"
            + "('Muy_alta', 'eficiencia', 'trapezoidal'),"
            + "('Muy_alta', 'elaboracion_productos_panaderia', 'trapezoidal'),"
            + "('Muy_alta', 'empatia', 'trapezoidal'),"
            + "('Muy_alta', 'especificaciones_tecnicas', 'trapezoidal'),"
            + "('Muy_alta', 'habilidad_lectoescritura', 'trapezoidal'),"
            + "('Muy_alta', 'habilidad_logicomatematica', 'trapezoidal'),"
            + "('Muy_alta', 'hornear_masas', 'trapezoidal'),"
            + "('Muy_alta', 'identificar_documentos_mercantiles', 'trapezoidal'),"
            + "('Muy_alta', 'integridad', 'trapezoidal'),"
            + "('Muy_alta', 'lenguaje_formal', 'trapezoidal'),"
            + "('Muy_alta', 'moler_cortar_carne', 'trapezoidal'),"
            + "('Muy_alta', 'motivacion', 'trapezoidal'),"
            + "('Muy_alta', 'normas_higiene_seguridad', 'trapezoidal'),"
            + "('Muy_alta', 'normativa_procedimientos', 'trapezoidal'),"
            + "('Muy_alta', 'norma_sanitaria_establecimientos', 'trapezoidal'),"
            + "('Muy_alta', 'pesaje_sellado_productos', 'trapezoidal'),"
            + "('Muy_alta', 'preparacion_masas', 'trapezoidal'),"
            + "('Muy_alta', 'presentacion_personal', 'trapezoidal'),"
            + "('Muy_alta', 'proactividad', 'trapezoidal'),"
            + "('Muy_alta', 'respeto', 'trapezoidal'),"
            + "('Muy_alta', 'responsabilidad', 'trapezoidal'),"
            + "('Muy_alta', 'sistema_informatico', 'trapezoidal'),"
            + "('Muy_alta', 'sociabilidad', 'trapezoidal'),"
            + "('Muy_alta', 'tecnicas_venta', 'trapezoidal'),"
            + "('Muy_alta', 'tolerancia_presion', 'trapezoidal'),"
            + "('Muy_alta', 'trabajo_equipo', 'trapezoidal'),"
            + "('Muy_baja', 'adaptacion_cambio', 'trapezoidal'),"
            + "('Muy_baja', 'almacenaje_traslado_mercaderia', 'trapezoidal'),"
            + "('Muy_baja', 'atencion_clientes', 'trapezoidal'),"
            + "('Muy_baja', 'autocontrol', 'trapezoidal'),"
            + "('Muy_baja', 'conocimientos_matematicas', 'trapezoidal'),"
            + "('Muy_baja', 'conocimiento_cajas', 'trapezoidal'),"
            + "('Muy_baja', 'disposicion_at_insumos', 'trapezoidal'),"
            + "('Muy_baja', 'eficiencia', 'trapezoidal'),"
            + "('Muy_baja', 'elaboracion_productos_panaderia', 'trapezoidal'),"
            + "('Muy_baja', 'empatia', 'trapezoidal'),"
            + "('Muy_baja', 'especificaciones_tecnicas', 'trapezoidal'),"
            + "('Muy_baja', 'habilidad_lectoescritura', 'trapezoidal'),"
            + "('Muy_baja', 'habilidad_logicomatematica', 'trapezoidal'),"
            + "('Muy_baja', 'hornear_masas', 'trapezoidal'),"
            + "('Muy_baja', 'identificar_documentos_mercantiles', 'trapezoidal'),"
            + "('Muy_baja', 'integridad', 'trapezoidal'),"
            + "('Muy_baja', 'lenguaje_formal', 'trapezoidal'),"
            + "('Muy_baja', 'moler_cortar_carne', 'trapezoidal'),"
            + "('Muy_baja', 'motivacion', 'trapezoidal'),"
            + "('Muy_baja', 'normas_higiene_seguridad', 'trapezoidal'),"
            + "('Muy_baja', 'normativa_procedimientos', 'trapezoidal'),"
            + "('Muy_baja', 'norma_sanitaria_establecimientos', 'trapezoidal'),"
            + "('Muy_baja', 'pesaje_sellado_productos', 'trapezoidal'),"
            + "('Muy_baja', 'preparacion_masas', 'trapezoidal'),"
            + "('Muy_baja', 'presentacion_personal', 'trapezoidal'),"
            + "('Muy_baja', 'proactividad', 'trapezoidal'),"
            + "('Muy_baja', 'respeto', 'trapezoidal'),"
            + "('Muy_baja', 'responsabilidad', 'trapezoidal'),"
            + "('Muy_baja', 'sistema_informatico', 'trapezoidal'),"
            + "('Muy_baja', 'sociabilidad', 'trapezoidal'),"
            + "('Muy_baja', 'tecnicas_venta', 'trapezoidal'),"
            + "('Muy_baja', 'tolerancia_presion', 'trapezoidal'),"
            + "('Muy_baja', 'trabajo_equipo', 'trapezoidal'),"
            + "('No', 'discapacidad_fisica', 'triangular'),"
            + "('Promedio', 'adaptacion_cambio', 'triangular'),"
            + "('Promedio', 'almacenaje_traslado_mercaderia', 'triangular'),"
            + "('Promedio', 'atencion_clientes', 'triangular'),"
            + "('Promedio', 'autocontrol', 'triangular'),"
            + "('Promedio', 'conocimientos_matematicas', 'triangular'),"
            + "('Promedio', 'conocimiento_cajas', 'triangular'),"
            + "('Promedio', 'disposicion_at_insumos', 'triangular'),"
            + "('Promedio', 'eficiencia', 'triangular'),"
            + "('Promedio', 'elaboracion_productos_panaderia', 'triangular'),"
            + "('Promedio', 'empatia', 'triangular'),"
            + "('Promedio', 'especificaciones_tecnicas', 'triangular'),"
            + "('Promedio', 'habilidad_lectoescritura', 'triangular'),"
            + "('Promedio', 'habilidad_logicomatematica', 'triangular'),"
            + "('Promedio', 'hornear_masas', 'triangular'),"
            + "('Promedio', 'identificar_documentos_mercantiles', 'triangular'),"
            + "('Promedio', 'integridad', 'triangular'),"
            + "('Promedio', 'lenguaje_formal', 'triangular'),"
            + "('Promedio', 'moler_cortar_carne', 'triangular'),"
            + "('Promedio', 'motivacion', 'triangular'),"
            + "('Promedio', 'normas_higiene_seguridad', 'triangular'),"
            + "('Promedio', 'normativa_procedimientos', 'triangular'),"
            + "('Promedio', 'norma_sanitaria_establecimientos', 'triangular'),"
            + "('Promedio', 'pesaje_sellado_productos', 'triangular'),"
            + "('Promedio', 'preparacion_masas', 'triangular'),"
            + "('Promedio', 'presentacion_personal', 'triangular'),"
            + "('Promedio', 'proactividad', 'triangular'),"
            + "('Promedio', 'respeto', 'triangular'),"
            + "('Promedio', 'responsabilidad', 'triangular'),"
            + "('Promedio', 'sistema_informatico', 'triangular'),"
            + "('Promedio', 'sociabilidad', 'triangular'),"
            + "('Promedio', 'tecnicas_venta', 'triangular'),"
            + "('Promedio', 'tolerancia_presion', 'triangular'),"
            + "('Promedio', 'trabajo_equipo', 'triangular'),"
            + "('Si', 'discapacidad_fisica', 'triangular');";
            cmd.ExecuteNonQuery();

            cmd.CommandText = "INSERT INTO `funciontrapezoide` (`nombreVariableLing`, `nombreValorLing`, `valorInferiorIzquierdo`, `valorSuperiorIzquierdo`, `valorSuperiorDerecho`, `valorInferiorDerecho`) VALUES"
            + "('adaptacion_cambio', 'Muy_alta', 70, 90, 100, 100),"
            + "('adaptacion_cambio', 'Muy_baja', 0, 0, 10, 30),"
            + "('almacenaje_traslado_mercaderia', 'Muy_alta', 70, 90, 100, 100),"
            + "('almacenaje_traslado_mercaderia', 'Muy_baja', 0, 0, 10, 30),"
            + "('atencion_clientes', 'Muy_alta', 70, 90, 100, 100),"
            + "('atencion_clientes', 'Muy_baja', 0, 0, 10, 30),"
            + "('autocontrol', 'Muy_alta', 70, 90, 100, 100),"
            + "('autocontrol', 'Muy_baja', 0, 0, 10, 30),"
            + "('conocimientos_matematicas', 'Muy_alta', 70, 90, 100, 100),"
            + "('conocimientos_matematicas', 'Muy_baja', 0, 0, 10, 30),"
            + "('conocimiento_cajas', 'Muy_alta', 70, 90, 100, 100),"
            + "('conocimiento_cajas', 'Muy_baja', 0, 0, 10, 30),"
            + "('disposicion_at_insumos', 'Muy_alta', 70, 90, 100, 100),"
            + "('disposicion_at_insumos', 'Muy_baja', 0, 0, 10, 30),"
            + "('eficiencia', 'Muy_alta', 70, 90, 100, 100),"
            + "('eficiencia', 'Muy_baja', 0, 0, 10, 30),"
            + "('elaboracion_productos_panaderia', 'Muy_alta', 70, 90, 100, 100),"
            + "('elaboracion_productos_panaderia', 'Muy_baja', 0, 0, 10, 30),"
            + "('empatia', 'Muy_alta', 70, 90, 100, 100),"
            + "('empatia', 'Muy_baja', 0, 0, 10, 30),"
            + "('especificaciones_tecnicas', 'Muy_alta', 70, 90, 100, 100),"
            + "('especificaciones_tecnicas', 'Muy_baja', 0, 0, 10, 30),"
            + "('habilidad_lectoescritura', 'Muy_alta', 70, 90, 100, 100),"
            + "('habilidad_lectoescritura', 'Muy_baja', 0, 0, 10, 30),"
            + "('habilidad_logicomatematica', 'Muy_alta', 70, 90, 100, 100),"
            + "('habilidad_logicomatematica', 'Muy_baja', 0, 0, 10, 30),"
            + "('hornear_masas', 'Muy_alta', 70, 90, 100, 100),"
            + "('hornear_masas', 'Muy_baja', 0, 0, 10, 30),"
            + "('identificar_documentos_mercantiles', 'Muy_alta', 70, 90, 100, 100),"
            + "('identificar_documentos_mercantiles', 'Muy_baja', 0, 0, 10, 30),"
            + "('integridad', 'Muy_alta', 70, 90, 100, 100),"
            + "('integridad', 'Muy_baja', 0, 0, 10, 30),"
            + "('lenguaje_formal', 'Muy_alta', 70, 90, 100, 100),"
            + "('lenguaje_formal', 'Muy_baja', 0, 0, 10, 30),"
            + "('moler_cortar_carne', 'Muy_alta', 70, 90, 100, 100),"
            + "('moler_cortar_carne', 'Muy_baja', 0, 0, 10, 30),"
            + "('motivacion', 'Muy_alta', 70, 90, 100, 100),"
            + "('motivacion', 'Muy_baja', 0, 0, 10, 30),"
            + "('normas_higiene_seguridad', 'Muy_alta', 70, 90, 100, 100),"
            + "('normas_higiene_seguridad', 'Muy_baja', 0, 0, 10, 30),"
            + "('normativa_procedimientos', 'Muy_alta', 70, 90, 100, 100),"
            + "('normativa_procedimientos', 'Muy_baja', 0, 0, 10, 30),"
            + "('norma_sanitaria_establecimientos', 'Muy_alta', 70, 90, 100, 100),"
            + "('norma_sanitaria_establecimientos', 'Muy_baja', 0, 0, 10, 30),"
            + "('pesaje_sellado_productos', 'Muy_alta', 70, 90, 100, 100),"
            + "('pesaje_sellado_productos', 'Muy_baja', 0, 0, 10, 30),"
            + "('preparacion_masas', 'Muy_alta', 70, 90, 100, 100),"
            + "('preparacion_masas', 'Muy_baja', 0, 0, 10, 30),"
            + "('presentacion_personal', 'Muy_alta', 70, 90, 100, 100),"
            + "('presentacion_personal', 'Muy_baja', 0, 0, 10, 30),"
            + "('proactividad', 'Muy_alta', 70, 90, 100, 100),"
            + "('proactividad', 'Muy_baja', 0, 0, 10, 30),"
            + "('respeto', 'Muy_alta', 70, 90, 100, 100),"
            + "('respeto', 'Muy_baja', 0, 0, 10, 30),"
            + "('responsabilidad', 'Muy_alta', 70, 90, 100, 100),"
            + "('responsabilidad', 'Muy_baja', 0, 0, 10, 30),"
            + "('sistema_informatico', 'Muy_alta', 70, 90, 100, 100),"
            + "('sistema_informatico', 'Muy_baja', 0, 0, 10, 30),"
            + "('sociabilidad', 'Muy_alta', 70, 90, 100, 100),"
            + "('sociabilidad', 'Muy_baja', 0, 0, 10, 30),"
            + "('tecnicas_venta', 'Muy_alta', 70, 90, 100, 100),"
            + "('tecnicas_venta', 'Muy_baja', 0, 0, 10, 30),"
            + "('tolerancia_presion', 'Muy_alta', 70, 90, 100, 100),"
            + "('tolerancia_presion', 'Muy_baja', 0, 0, 10, 30),"
            + "('trabajo_equipo', 'Muy_alta', 70, 90, 100, 100),"
            + "('trabajo_equipo', 'Muy_baja', 0, 0, 10, 30); ";
            cmd.ExecuteNonQuery();

            cmd.CommandText = "INSERT INTO `funciontriangular` (`nombreVariableLing`, `nombreValorLing`, `valorIzquierda`, `valorCentro`, `valorDerecha`) VALUES"
            + "('adaptacion_cambio', 'Alta', 50, 70, 90),"
            + "('adaptacion_cambio', 'Baja', 10, 30, 50),"
            + "('adaptacion_cambio', 'Promedio', 30, 50, 70),"
            + "('almacenaje_traslado_mercaderia', 'Alta', 50, 70, 90),"
            + "('almacenaje_traslado_mercaderia', 'Baja', 10, 30, 50),"
            + "('almacenaje_traslado_mercaderia', 'Promedio', 30, 50, 70),"
            + "('atencion_clientes', 'Alta', 50, 70, 90),"
            + "('atencion_clientes', 'Baja', 10, 30, 50),"
            + "('atencion_clientes', 'Promedio', 30, 50, 70),"
            + "('autocontrol', 'Alta', 50, 70, 90),"
            + "('autocontrol', 'Baja', 10, 30, 50),"
            + "('autocontrol', 'Promedio', 30, 50, 70),"
            + "('conocimientos_matematicas', 'Alta', 50, 70, 90),"
            + "('conocimientos_matematicas', 'Baja', 10, 30, 50),"
            + "('conocimientos_matematicas', 'Promedio', 30, 50, 70),"
            + "('conocimiento_cajas', 'Alta', 50, 70, 90),"
            + "('conocimiento_cajas', 'Baja', 10, 30, 50),"
            + "('conocimiento_cajas', 'Promedio', 30, 50, 70),"
            + "('discapacidad_fisica', 'No', 0, 0, 50),"
            + "('discapacidad_fisica', 'Si', 50, 100, 100),"
            + "('disposicion_at_insumos', 'Alta', 50, 70, 90),"
            + "('disposicion_at_insumos', 'Baja', 10, 30, 50),"
            + "('disposicion_at_insumos', 'Promedio', 30, 50, 70),"
            + "('edad', 'Adolescente', 18, 18, 24),"
            + "('edad', 'Adulto', 24, 40, 60),"
            + "('edad', 'Adulto_mayor', 55, 60, 60),"
            + "('edad', 'Joven_adulto', 20, 24, 40),"
            + "('eficiencia', 'Alta', 50, 70, 90),"
            + "('eficiencia', 'Baja', 10, 30, 50),"
            + "('eficiencia', 'Promedio', 30, 50, 70),"
            + "('elaboracion_productos_panaderia', 'Alta', 50, 70, 90),"
            + "('elaboracion_productos_panaderia', 'Baja', 10, 30, 50),"
            + "('elaboracion_productos_panaderia', 'Promedio', 30, 50, 70),"
            + "('empatia', 'Alta', 50, 70, 90),"
            + "('empatia', 'Baja', 10, 30, 50),"
            + "('empatia', 'Promedio', 30, 50, 70),"
            + "('especificaciones_tecnicas', 'Alta', 50, 70, 90),"
            + "('especificaciones_tecnicas', 'Baja', 10, 30, 50),"
            + "('especificaciones_tecnicas', 'Promedio', 30, 50, 70),"
            + "('habilidad_lectoescritura', 'Alta', 50, 70, 90),"
            + "('habilidad_lectoescritura', 'Baja', 10, 30, 50),"
            + "('habilidad_lectoescritura', 'Promedio', 30, 50, 70),"
            + "('habilidad_logicomatematica', 'Alta', 50, 70, 90),"
            + "('habilidad_logicomatematica', 'Baja', 10, 30, 50),"
            + "('habilidad_logicomatematica', 'Promedio', 30, 50, 70),"
            + "('hornear_masas', 'Alta', 50, 70, 90),"
            + "('hornear_masas', 'Baja', 10, 30, 50),"
            + "('hornear_masas', 'Promedio', 30, 50, 70),"
            + "('identificar_documentos_mercantiles', 'Alta', 50, 70, 90),"
            + "('identificar_documentos_mercantiles', 'Baja', 10, 30, 50),"
            + "('identificar_documentos_mercantiles', 'Promedio', 30, 50, 70),"
            + "('integridad', 'Alta', 50, 70, 90),"
            + "('integridad', 'Baja', 10, 30, 50),"
            + "('integridad', 'Promedio', 30, 50, 70),"
            + "('lenguaje_formal', 'Alta', 50, 70, 90),"
            + "('lenguaje_formal', 'Baja', 10, 30, 50),"
            + "('lenguaje_formal', 'Promedio', 30, 50, 70),"
            + "('moler_cortar_carne', 'Alta', 50, 70, 90),"
            + "('moler_cortar_carne', 'Baja', 10, 30, 50),"
            + "('moler_cortar_carne', 'Promedio', 30, 50, 70),"
            + "('motivacion', 'Alta', 50, 70, 90),"
            + "('motivacion', 'Baja', 10, 30, 50),"
            + "('motivacion', 'Promedio', 30, 50, 70),"
            + "('normas_higiene_seguridad', 'Alta', 50, 70, 90),"
            + "('normas_higiene_seguridad', 'Baja', 10, 30, 50),"
            + "('normas_higiene_seguridad', 'Promedio', 30, 50, 70),"
            + "('normativa_procedimientos', 'Alta', 50, 70, 90),"
            + "('normativa_procedimientos', 'Baja', 10, 30, 50),"
            + "('normativa_procedimientos', 'Promedio', 30, 50, 70),"
            + "('norma_sanitaria_establecimientos', 'Alta', 50, 70, 90),"
            + "('norma_sanitaria_establecimientos', 'Baja', 10, 30, 50),"
            + "('norma_sanitaria_establecimientos', 'Promedio', 30, 50, 70),"
            + "('pesaje_sellado_productos', 'Alta', 50, 70, 90),"
            + "('pesaje_sellado_productos', 'Baja', 10, 30, 50),"
            + "('pesaje_sellado_productos', 'Promedio', 30, 50, 70),"
            + "('preparacion_masas', 'Alta', 50, 70, 90),"
            + "('preparacion_masas', 'Baja', 10, 30, 50),"
            + "('preparacion_masas', 'Promedio', 30, 50, 70),"
            + "('presentacion_personal', 'Alta', 50, 70, 90),"
            + "('presentacion_personal', 'Baja', 10, 30, 50),"
            + "('presentacion_personal', 'Promedio', 30, 50, 70),"
            + "('proactividad', 'Alta', 50, 70, 90),"
            + "('proactividad', 'Baja', 10, 30, 50),"
            + "('proactividad', 'Promedio', 30, 50, 70),"
            + "('respeto', 'Alta', 50, 70, 90),"
            + "('respeto', 'Baja', 10, 30, 50),"
            + "('respeto', 'Promedio', 30, 50, 70),"
            + "('responsabilidad', 'Alta', 50, 70, 90),"
            + "('responsabilidad', 'Baja', 10, 30, 50),"
            + "('responsabilidad', 'Promedio', 30, 50, 70),"
            + "('sistema_informatico', 'Alta', 50, 70, 90),"
            + "('sistema_informatico', 'Baja', 10, 30, 50),"
            + "('sistema_informatico', 'Promedio', 30, 50, 70),"
            + "('sociabilidad', 'Alta', 50, 70, 90),"
            + "('sociabilidad', 'Baja', 10, 30, 50),"
            + "('sociabilidad', 'Promedio', 30, 50, 70),"
            + "('tecnicas_venta', 'Alta', 50, 70, 90),"
            + "('tecnicas_venta', 'Baja', 10, 30, 50),"
            + "('tecnicas_venta', 'Promedio', 30, 50, 70),"
            + "('tolerancia_presion', 'Alta', 50, 70, 90),"
            + "('tolerancia_presion', 'Baja', 10, 30, 50),"
            + "('tolerancia_presion', 'Promedio', 30, 50, 70),"
            + "('trabajo_equipo', 'Alta', 50, 70, 90),"
            + "('trabajo_equipo', 'Baja', 10, 30, 50),"
            + "('trabajo_equipo', 'Promedio', 30, 50, 70);";
            cmd.ExecuteNonQuery();

            for (int i = 1; i < 109; i++)
            {
                cmd.CommandText = "INSERT INTO alternativasPreguntas(idPregunta, alternativa) VALUES" +
                    "(" + i + ", 'Altamente competente'),"
                    + "(" + i + ", 'Competente'),"
                    + "(" + i + ", 'Frecuente'),"
                    + "(" + i + ", 'La mitad del tiempo'),"
                    + "(" + i + ", 'Modelo de rol'),"
                    + "(" + i + ", 'Necesita desarrollarse'),"
                    + "(" + i + ", 'Necesita desarrollarse significativamente'),"
                    + "(" + i + ", 'No puede ser evaluado'),"
                    + "(" + i + ", 'Ocasional'),"
                    + "(" + i + ", 'Siempre');";
                cmd.ExecuteNonQuery();
            }

            conn.Close();

            /*
            cmd.CommandText = "";
            cmd.ExecuteNonQuery();

            cmd.CommandText = "";
            cmd.ExecuteNonQuery();

            cmd.CommandText = "";
            cmd.ExecuteNonQuery();
            */
        }
    }
}
